# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: asyncViridian-home
description: |
  This is the personal website of Joyce Zhou.
  </br>
  Based on a <a href="https://hackcss.egoist.moe/">Hack CSS</a> Jekyll <a href="https://github.com/wemake-services/jekyll-theme-hackcss">theme</a>.
repository: https://github.com/asyncViridian/asyncviridian.github.io/
baseurl: /  # the subpath of your site, e.g. /blog
url: https://asyncviridian.github.io/  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: 'Joyce Zhou'
email: jyzhou15 (at) cs.washington.edu

navigation:
  - text: About
    url: /
  # - text: CV
  #   url: /documents/cv.pdf
  # - text: Projects
  #   url: /projects
  - text: Blog
    url: /blog
  # - text: Examples
  #   url: /examples
  # - text: Docs
  #   url: /docs

projects:
  # - name: git-secret
  #   description: A bash-tool to store your private data inside a git repository.
  #   link: https://sobolevn.github.io/git-secret
  #   image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
  # - name: awesome-cryptography
  #   description: A curated list of cryptography resources and links.
  #   link: https://github.com/sobolevn/awesome-cryptography
  #   image: https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg
  # - name: ecto_autoslug_field
  #   description: Automatically creates slugs for your Ecto models.
  #   link: https://github.com/sobolevn/ecto_autoslug_field
  # - name: django-split-settings
  #   description: Organize Django settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files.
  #   link: https://github.com/sobolevn/django-split-settings

social:
  - service: github
    username: asyncViridian
    link: https://github.com/asyncViridian

# Plugins
plugins:
  - jekyll-seo-tag
